import axios from 'axios';
import dotenv from 'dotenv';
import { APIResilience } from '../utils/APIResilience.js';

dotenv.config();

export class GeminiService {
    private apiKey: string;
    private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models';

    constructor() {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error('GEMINI_API_KEY is missing in .env');
        }
        this.apiKey = apiKey;
    }

    async generateContent(prompt: string): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                const url = `${this.baseUrl}/gemini-2.0-flash-lite:generateContent?key=${this.apiKey}`;

                const response = await axios.post(
                    url,
                    {
                        contents: [{
                            parts: [{
                                text: prompt
                            }]
                        }]
                    },
                    {
                        timeout: 45000, // 45 second timeout for Gemini
                        headers: {
                            'Content-Type': 'application/json'
                        }
                    }
                );

                const content = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
                
                if (!content) {
                    throw new Error('No response generated by Gemini API');
                }
                
                return content;
            },
            { maxRetries: 2, timeoutMs: 50000 },
            'Gemini API'
        );
    }
}
