import OpenAI from 'openai';
import dotenv from 'dotenv';
import { APIResilience } from '../utils/APIResilience.js';
import { SearchService } from './SearchService.js';

dotenv.config();

export interface WebSearchOptions {
    query: string;
    mode?: 'weak' | 'agentic' | 'deep-research';
    reasoningLevel?: 'low' | 'medium' | 'high';
    model?: string;
}

export interface SearchResult {
    content: string;
    model: string;
    mode: string;
    tokensUsed: number | undefined;
    searchDepth: string | undefined;
}

export class OpenAIService {
    private openai: OpenAI;
    private searchService: SearchService;

    constructor() {
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
            throw new Error('OPENAI_API_KEY is missing in .env');
        }
        this.openai = new OpenAI({ 
            apiKey,
            timeout: 45000, // 45 second default timeout
            maxRetries: 0 // We handle retries ourselves
        });
        this.searchService = new SearchService();
    }

    /**
     * Legacy method for backward compatibility
     */
    async getCompletion(prompt: string): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                const response = await this.openai.chat.completions.create({
                    model: 'gpt-4o-mini',
                    messages: [{ role: 'user', content: prompt }],
                });

                const content = response.choices[0]?.message?.content;
                
                if (!content) {
                    throw new Error('No response generated by OpenAI');
                }
                
                return content;
            },
            { maxRetries: 2, timeoutMs: 50000 },
            'OpenAI ChatGPT'
        );
    }

    /**
     * Enhanced web search with agentic reasoning and deep research
     * Uses optimized searching for medium level (fast & efficient)
     */
    async agenticWebSearch(options: WebSearchOptions): Promise<SearchResult> {
        const mode = options.mode || 'agentic';
        const reasoningLevel = options.reasoningLevel || 'medium';
        
        // Select model based on mode and reasoning level
        let model = options.model;
        let timeout = 50000; // Default 50 seconds
        let maxRetries = 2;
        let numSearches = 3; // Optimized for speed

        if (!model) {
            if (mode === 'deep-research') {
                model = 'gpt-4o';
                timeout = 300000; // 5 minutes for deep research
                maxRetries = 1;
                numSearches = 10;
            } else if (mode === 'agentic') {
                // Agentic search with reasoning - optimized for speed and cost
                model = 'gpt-4o-mini';
                if (reasoningLevel === 'high') {
                    timeout = 90000; // 1.5 minutes for high reasoning
                    numSearches = 5;
                } else if (reasoningLevel === 'medium') {
                    timeout = 45000; // 45 seconds for medium reasoning (optimized)
                    numSearches = 3; // Reduced from 5 for speed
                } else {
                    timeout = 30000;
                    numSearches = 2;
                }
            } else {
                // Weak/quick search
                model = 'gpt-4o-mini';
                timeout = 30000;
                numSearches = 2;
            }
        }

        console.log(`   Model: ${model}`);
        console.log(`   Reasoning Level: ${reasoningLevel}`);
        console.log(`   🌐 Using Tavily API for live web searches...`);
        if (mode === 'deep-research') {
            console.log(`   ⚠️  Deep research may take several minutes...\n`);
        } else if (mode === 'agentic') {
            console.log(`   🤖 Agentic mode will analyze live search results...\n`);
        }

        return APIResilience.executeWithRetry(
            async () => {
                const startTime = Date.now();
                
                // Perform live web searches via Tavily
                const searchResults = await this.performLiveSearches(options.query, numSearches, reasoningLevel);
                
                const searchTime = ((Date.now() - startTime) / 1000).toFixed(1);
                console.log(`   ✓ Completed ${numSearches} live searches in ${searchTime}s`);
                console.log(`   🤖 Analyzing results with AI...\n`);
                
                // Analyze search results with AI
                const analysisPrompt = this.buildAnalysisPrompt(options.query, searchResults, mode, reasoningLevel);
                
                const response = await this.openai.chat.completions.create({
                    model: model,
                    messages: [{ 
                        role: 'user', 
                        content: analysisPrompt 
                    }],
                    temperature: mode === 'deep-research' ? 0.3 : 0.7,
                });

                const content = response.choices[0]?.message?.content;
                
                if (!content) {
                    throw new Error('No response generated by OpenAI');
                }

                const elapsedTime = ((Date.now() - startTime) / 1000).toFixed(1);
                console.log(`   ✓ Search completed in ${elapsedTime}s total`);
                
                return {
                    content,
                    model: model,
                    mode: mode,
                    tokensUsed: response.usage?.total_tokens ?? undefined,
                    searchDepth: reasoningLevel,
                };
            },
            { maxRetries, timeoutMs: timeout },
            `OpenAI ${mode} Search`
        );
    }

    /**
     * Build search prompt for OpenAI knowledge synthesis
     */
    private buildSearchPrompt(query: string, mode: string, reasoningLevel: string): string {
        if (mode === 'deep-research') {
            return `Provide comprehensive research and analysis on: "${query}"

Use your knowledge to gather information as if from multiple authoritative sources.

Requirements:
- Provide detailed, fact-based answers
- Include statistics, dates, and specific examples where relevant
- Organize findings into clear sections
- Note what information might be outdated based on your knowledge cutoff
- Conclude with a summary of key findings

Deliver a thorough research report.`;
        } else if (mode === 'agentic') {
            const instructions = {
                low: 'Provide a concise summary with key facts.',
                medium: 'Analyze from multiple perspectives and synthesize findings with supporting details.',
                high: 'Deeply analyze all perspectives, evaluate information credibility, and provide comprehensive analysis.'
            };

            return `Provide comprehensive information about: "${query}"

Reasoning Level: ${reasoningLevel}
Instructions: ${instructions[reasoningLevel as keyof typeof instructions]}

Requirements:
- Provide current, accurate information based on your knowledge
- Share specific facts, statistics, and examples
- Structure response clearly
- Note your knowledge cutoff date if relevant
- Include confidence levels where appropriate`;
        } else {
            // Quick search
            return `Provide information about: "${query}"

Include:
- Direct answer to the query
- Key facts and statistics (3-5 main points)
- Brief, factual summary

Focus on accurate, relevant information from your knowledge base.`;
        }
    }

    /**
     * Perform multiple live web searches with query variations
     */
    private async performLiveSearches(
        originalQuery: string, 
        numSearches: number,
        reasoningLevel: string
    ): Promise<string> {
        const queries: string[] = [originalQuery];
        
        // Generate query variations for more comprehensive search
        if (numSearches > 1) {
            if (reasoningLevel === 'medium' || reasoningLevel === 'high') {
                queries.push(`${originalQuery} information`);
                queries.push(`${originalQuery} details`);
            }
            if (reasoningLevel === 'high') {
                queries.push(`${originalQuery} overview`);
                queries.push(`${originalQuery} about`);
                queries.push(`${originalQuery} facts`);
                queries.push(`what is ${originalQuery}`);
            }
        }
        
        // Limit to requested number of searches
        const searchQueries = queries.slice(0, numSearches);
        
        // Perform all searches
        const searchPromises = searchQueries.map(async (query, index) => {
            try {
                console.log(`   🔍 Search ${index + 1}/${searchQueries.length}: "${query}"`);
                const results = await this.searchService.search(query);
                return `\n=== Search ${index + 1}: "${query}" ===\n${results}`;
            } catch (error: any) {
                console.warn(`   ⚠️  Search ${index + 1} failed: ${error.message}`);
                return `\n=== Search ${index + 1}: "${query}" ===\nSearch failed: ${error.message}`;
            }
        });
        
        const results = await Promise.all(searchPromises);
        return results.join('\n\n');
    }

    /**
     * Build analysis prompt for AI to analyze live search results
     */
    private buildAnalysisPrompt(
        query: string, 
        searchResults: string, 
        mode: string, 
        reasoningLevel: string
    ): string {
        const basePrompt = `You are an expert research analyst. I have performed live web searches using Tavily API and need you to analyze the results.

Original Query: "${query}"

LIVE SEARCH RESULTS FROM TAVILY:
${searchResults}

`;

        if (mode === 'deep-research') {
            return basePrompt + `Your Task: Conduct comprehensive analysis
- Synthesize information from all search results
- Identify key themes and patterns
- Provide detailed insights with specific examples
- Include source citations with URLs
- Organize findings into clear sections
- Note any conflicting information
- Conclude with key findings summary

Deliver a thorough, well-structured research analysis.`;
        } else if (mode === 'agentic') {
            if (reasoningLevel === 'high') {
                return basePrompt + `Your Task: Deep analytical synthesis
- Analyze all search results comprehensively
- Evaluate source credibility and relevance
- Cross-reference information across sources
- Identify patterns, trends, and insights
- Provide detailed explanations with citations
- Note confidence levels and data quality
- Conclude with comprehensive synthesis`;
            } else if (reasoningLevel === 'medium') {
                return basePrompt + `Your Task: Balanced analysis and synthesis
- Analyze key information from the search results
- Synthesize main findings into clear points
- Include relevant citations and URLs
- Provide context and brief explanations
- Note any important patterns or insights
- Conclude with a concise summary`;
            } else {
                return basePrompt + `Your Task: Quick summary
- Extract the most relevant information
- Provide a concise summary
- Include 3-5 key points
- Cite main sources with URLs
- Keep it focused and actionable`;
            }
        } else {
            // Quick search
            return basePrompt + `Your Task: Quick factual summary
- Provide direct answer to the query
- List key facts and information
- Include top 3-5 source URLs
- Keep it brief and factual`;
        }
    }

    /**
     * Get search mode display name
     */
    static getModeName(mode: string): string {
        const names: Record<string, string> = {
            'weak': 'Weak Search',
            'agentic': 'Agentic Reasoning Search',
            'deep-research': 'Deep Research'
        };
        return names[mode] || mode;
    }
}
