import OpenAI from 'openai';
import dotenv from 'dotenv';
import { APIResilience } from '@cli-ai-toolkit/utils';

dotenv.config();

export interface WebSearchOptions {
    query: string;
    mode?: 'weak' | 'agentic' | 'deep-research';
    reasoningLevel?: 'low' | 'medium' | 'high';
    model?: string;
}

export interface SearchResult {
    content: string;
    model: string;
    mode: string;
    tokensUsed: number | undefined;
    searchDepth: string | undefined;
}

export class OpenAIService {
    private openai: OpenAI;

    constructor() {
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
            throw new Error('OPENAI_API_KEY is missing in .env');
        }
        this.openai = new OpenAI({ 
            apiKey,
            timeout: 45000, // 45 second default timeout
            maxRetries: 0 // We handle retries ourselves
        });
    }

    /**
     * Legacy method for backward compatibility
     */
    async getCompletion(prompt: string): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                const response = await this.openai.chat.completions.create({
                    model: 'gpt-4o-mini',
                    messages: [{ role: 'user', content: prompt }],
                });

                const content = response.choices[0]?.message?.content;
                
                if (!content) {
                    throw new Error('No response generated by OpenAI');
                }
                
                return content;
            },
            { maxRetries: 2, timeoutMs: 50000 },
            'OpenAI ChatGPT'
        );
    }

    /**
     * Enhanced web search with agentic reasoning and deep research
     */
    async agenticWebSearch(options: WebSearchOptions): Promise<SearchResult> {
        const mode = options.mode || 'agentic';
        const reasoningLevel = options.reasoningLevel || 'medium';
        
        // Select model based on mode and reasoning level
        let model = options.model;
        let timeout = 50000; // Default 50 seconds
        let maxRetries = 2;

        if (!model) {
            if (mode === 'deep-research') {
                // Deep research uses specialized models
                model = 'gpt-4o'; // Fallback to gpt-4o if o3/gpt-5 not available
                timeout = 300000; // 5 minutes for deep research
                maxRetries = 1; // Less retries for long operations
            } else if (mode === 'agentic') {
                // Agentic search with reasoning
                if (reasoningLevel === 'high') {
                    model = 'gpt-4o';
                    timeout = 180000; // 3 minutes for high reasoning
                } else {
                    model = 'gpt-4o-mini';
                    timeout = 90000; // 1.5 minutes for medium/low reasoning
                }
            } else {
                // Weak/quick search
                model = 'gpt-4o-mini';
                timeout = 50000;
            }
        }

        const prompt = this.buildSearchPrompt(options.query, mode, reasoningLevel);

        console.log(`   Model: ${model}`);
        console.log(`   Reasoning Level: ${reasoningLevel}`);
        if (mode === 'deep-research') {
            console.log(`   ⚠️  Deep research may take several minutes...\n`);
        } else if (mode === 'agentic') {
            console.log(`   🤖 Agentic search will analyze and search iteratively...\n`);
        }

        return APIResilience.executeWithRetry(
            async () => {
                const startTime = Date.now();
                
                const response = await this.openai.chat.completions.create({
                    model: model,
                    messages: [{ 
                        role: 'user', 
                        content: prompt 
                    }],
                    temperature: mode === 'deep-research' ? 0.3 : 0.7, // Lower temp for research
                });

                const content = response.choices[0]?.message?.content;
                
                if (!content) {
                    throw new Error('No response generated by OpenAI');
                }

                const elapsedTime = ((Date.now() - startTime) / 1000).toFixed(1);
                console.log(`   ✓ Search completed in ${elapsedTime}s`);
                
                return {
                    content,
                    model: model,
                    mode: mode,
                    tokensUsed: response.usage?.total_tokens ?? undefined,
                    searchDepth: reasoningLevel,
                };
            },
            { maxRetries, timeoutMs: timeout },
            `OpenAI ${mode} Search`
        );
    }

    /**
     * Build search prompt based on mode and reasoning level
     */
    private buildSearchPrompt(query: string, mode: string, reasoningLevel: string): string {
        if (mode === 'deep-research') {
            return `You are a deep research assistant. Conduct comprehensive research on the following query. 

Query: "${query}"

Instructions:
1. Search multiple authoritative sources (aim for 10+ sources)
2. Analyze and synthesize information from different perspectives
3. Provide detailed, fact-based answers with citations
4. Include statistics, dates, and specific examples where relevant
5. Organize findings into clear sections
6. Conclude with a summary of key findings

Deliver a thorough research report.`;
        } else if (mode === 'agentic') {
            const reasoningInstructions = {
                low: 'Perform 2-3 targeted searches and provide a concise summary.',
                medium: 'Perform 5-7 searches, analyze results, and synthesize findings with supporting details.',
                high: 'Perform 10+ searches, deeply analyze all perspectives, evaluate source credibility, and provide comprehensive analysis with extensive citations.'
            };

            return `You are an agentic search assistant with web access. Use your reasoning abilities to search and analyze information.

Query: "${query}"

Reasoning Level: ${reasoningLevel}
Instructions: ${reasoningInstructions[reasoningLevel as keyof typeof reasoningInstructions]}

Provide:
- Search strategy used
- Key findings from multiple sources
- Source citations (URLs when possible)
- Synthesized conclusions
- Confidence level in findings`;
        } else {
            // Quick search
            return `Search the web and provide factual sources and summaries for: ${query}

Provide:
- Direct answer to the query
- Key facts and statistics
- 3-5 relevant source citations
- Brief summary`;
        }
    }

    /**
     * Get search mode display name
     */
    static getModeName(mode: string): string {
        const names: Record<string, string> = {
            'weak': 'Weak Search',
            'agentic': 'Agentic Reasoning Search',
            'deep-research': 'Deep Research'
        };
        return names[mode] || mode;
    }
}
