import axios from 'axios';
import dotenv from 'dotenv';
import fs from 'fs/promises';
import { APIResilience } from '@cli-ai-toolkit/utils';

dotenv.config();

export interface ImageComparisonResult {
    pass: boolean;
    score: number;
    notes: string;
}

export class GeminiService {
    private apiKey: string;
    private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models';

    constructor() {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error('GEMINI_API_KEY is missing in .env');
        }
        this.apiKey = apiKey;
    }

    async generateContent(prompt: string): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                const url = `${this.baseUrl}/gemini-2.0-flash-lite:generateContent?key=${this.apiKey}`;

                const response = await axios.post(
                    url,
                    {
                        contents: [{
                            parts: [{
                                text: prompt
                            }]
                        }]
                    },
                    {
                        timeout: 45000, // 45 second timeout for Gemini
                        headers: {
                            'Content-Type': 'application/json'
                        }
                    }
                );

                const content = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
                
                if (!content) {
                    throw new Error('No response generated by Gemini API');
                }
                
                return content;
            },
            { maxRetries: 2, timeoutMs: 50000 },
            'Gemini API'
        );
    }

    /**
     * Compare two images based on a goal/criteria
     * @param goal - The evaluation criteria
     * @param targetImagePath - Path to the target/reference image
     * @param candidateImagePath - Path to the candidate image to evaluate
     * @returns Comparison result with pass/fail, score, and notes
     */
    async compareImages(
        goal: string,
        targetImagePath: string,
        candidateImagePath: string
    ): Promise<ImageComparisonResult> {
        return APIResilience.executeWithRetry(
            async () => {
                // Read and encode images as base64
                const targetBuffer = await fs.readFile(targetImagePath);
                const candidateBuffer = await fs.readFile(candidateImagePath);
                
                const targetBase64 = targetBuffer.toString('base64');
                const candidateBase64 = candidateBuffer.toString('base64');

                // Determine MIME type (assume PNG/JPEG)
                const targetMime = targetImagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';
                const candidateMime = candidateImagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

                const url = `${this.baseUrl}/gemini-2.0-flash-lite:generateContent?key=${this.apiKey}`;

                const prompt = `You are an image comparison judge. Compare these two images based on the following goal/criteria:

GOAL: ${goal}

TARGET IMAGE (reference):
[First image]

CANDIDATE IMAGE (to evaluate):
[Second image]

Evaluate how well the candidate image meets the goal compared to the target image.

Respond in this EXACT JSON format (no markdown, no code blocks):
{
  "pass": true/false,
  "score": <number 0-100>,
  "notes": "Brief explanation of the evaluation"
}`;

                const response = await axios.post(
                    url,
                    {
                        contents: [{
                            parts: [
                                { text: prompt },
                                {
                                    inline_data: {
                                        mime_type: targetMime,
                                        data: targetBase64
                                    }
                                },
                                {
                                    inline_data: {
                                        mime_type: candidateMime,
                                        data: candidateBase64
                                    }
                                }
                            ]
                        }]
                    },
                    {
                        timeout: 60000, // 60 second timeout for vision tasks
                        headers: {
                            'Content-Type': 'application/json'
                        }
                    }
                );

                const content = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
                
                if (!content) {
                    throw new Error('No response generated by Gemini Vision API');
                }

                // Parse JSON response
                const cleaned = content.trim().replace(/```json\s*/g, '').replace(/```\s*/g, '');
                const result = JSON.parse(cleaned);

                return {
                    pass: result.pass === true,
                    score: Number(result.score) || 0,
                    notes: result.notes || 'No notes provided'
                };
            },
            { maxRetries: 2, timeoutMs: 70000 },
            'Gemini Vision API'
        );
    }
}
