import OpenAI from 'openai';
import dotenv from 'dotenv';
import fs from 'fs/promises';
import { APIResilience } from '@cli-ai-toolkit/utils';

dotenv.config();

export class OpenAIVisionService {
    private openai: OpenAI;

    constructor() {
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
            throw new Error('OPENAI_API_KEY is missing in .env');
        }
        this.openai = new OpenAI({
            apiKey,
            timeout: 90000,
            maxRetries: 0
        });
    }

    /**
     * Generate HTML/CSS code from a screenshot using OpenAI Vision
     * @param screenshotPath - Path to the screenshot image
     * @param additionalContext - Optional context or revision notes
     * @returns Complete HTML with embedded CSS
     */
    async generateHTMLFromScreenshot(
        screenshotPath: string,
        additionalContext?: string
    ): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                // Read and encode image as base64
                const imageBuffer = await fs.readFile(screenshotPath);
                const imageBase64 = imageBuffer.toString('base64');

                // Determine MIME type
                const imageMime = screenshotPath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

                const basePrompt = `You are an expert web developer. Analyze this screenshot and recreate it as a complete, standalone HTML page with embedded CSS.

REQUIREMENTS:
1. Create a SINGLE HTML file with all CSS embedded in <style> tags
2. Match the layout, colors, typography, spacing, and styling EXACTLY
3. Use semantic HTML5 elements
4. Make it responsive and pixel-perfect
5. Include all visible text, buttons, images (use placeholder images if needed)
6. Use modern CSS (flexbox/grid where appropriate)
7. Match fonts as closely as possible (use web-safe fonts or Google Fonts)
8. Pay attention to: padding, margins, colors (exact hex values), font sizes, borders, shadows

${additionalContext ? `\nREVISION NOTES:\n${additionalContext}\n\nAddress these issues in your implementation.` : ''}

Output ONLY the complete HTML code. Do NOT include markdown code blocks or explanations. Start with <!DOCTYPE html>`;

                const response = await this.openai.chat.completions.create({
                    model: 'gpt-4o',
                    messages: [
                        {
                            role: 'user',
                            content: [
                                { type: 'text', text: basePrompt },
                                {
                                    type: 'image_url',
                                    image_url: {
                                        url: `data:${imageMime};base64,${imageBase64}`,
                                        detail: 'high'
                                    }
                                }
                            ]
                        }
                    ],
                    max_tokens: 4096,
                    temperature: 0.3
                });

                const content = response.choices[0]?.message?.content;

                if (!content) {
                    throw new Error('No response generated by OpenAI Vision API');
                }

                // Clean up markdown code blocks if present
                let cleaned = content.trim();
                cleaned = cleaned.replace(/^```html\s*/m, '');
                cleaned = cleaned.replace(/^```\s*/m, '');
                cleaned = cleaned.replace(/```\s*$/m, '');
                cleaned = cleaned.trim();

                // Validate it looks like HTML
                if (!cleaned.toLowerCase().includes('<!doctype html') && !cleaned.toLowerCase().includes('<html')) {
                    throw new Error('Generated content does not appear to be valid HTML');
                }

                return cleaned;
            },
            { maxRetries: 2, timeoutMs: 100000 },
            'OpenAI Vision API (HTML Generation)'
        );
    }

    /**
     * Compare two images and provide detailed critique
     * @param targetImagePath - Path to the target/reference image
     * @param candidateImagePath - Path to the candidate image
     * @param context - Optional context about what's being compared
     * @returns Detailed comparison
     */
    async compareImages(
        targetImagePath: string,
        candidateImagePath: string,
        context?: string
    ): Promise<string> {
        return APIResilience.executeWithRetry(
            async () => {
                // Read and encode images as base64
                const targetBuffer = await fs.readFile(targetImagePath);
                const candidateBuffer = await fs.readFile(candidateImagePath);

                const targetBase64 = targetBuffer.toString('base64');
                const candidateBase64 = candidateBuffer.toString('base64');

                const targetMime = targetImagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';
                const candidateMime = candidateImagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

                const prompt = `ROLE

You are a strict visual quality judge and UI/UX art director.

You NEVER generate code.
You NEVER modify files.
You ONLY evaluate and critique.

You analyze screenshots and determine:
- visual accuracy
- layout correctness
- typography precision
- color matching
- spacing consistency

---

TASK

Evaluate the provided screenshots.

Image A (TARGET):
The reference / expected UI
[First image]

Image B (CANDIDATE):
The generated UI to evaluate
[Second image]
${context ? `\nCONTEXT: ${context}` : ''}

Identify 5-10 CONCRETE, ACTIONABLE UI differences.

---

EVALUATION CRITERIA

Analyze:
- Layout: positioning, margins, padding, spacing
- Typography: font family, size, weight, line-height
- Colors: specific values, opacity
- Sizing: dimensions of elements
- Alignment issues
- Borders and styling

---

OUTPUT FORMAT

Return ONLY valid JSON:
{
  "summary": "Brief 1-2 sentence overview",
  "items": [
    {
      "priority": "critical|high|medium|low",
      "category": "layout|typography|colors|spacing|sizing|alignment|borders|other",
      "element": "Specific UI element name",
      "issue": "What's wrong",
      "expected": "What target shows (be specific)",
      "actual": "What candidate shows (be specific)"
    }
  ]
}

---

PRIORITY RULES

critical: breaks layout or makes UI unusable
high: very noticeable, affects user experience
medium: noticeable but minor impact
low: subtle difference, minimal impact

---

CRITICAL RULE

You do NOT generate code.
You ONLY describe what must be fixed.
The coding agent will use your instructions.
You are a judge, not a builder.`;

                const response = await this.openai.chat.completions.create({
                    model: 'gpt-4o',
                    messages: [
                        {
                            role: 'user',
                            content: [
                                { type: 'text', text: prompt },
                                {
                                    type: 'image_url',
                                    image_url: {
                                        url: `data:${targetMime};base64,${targetBase64}`,
                                        detail: 'high'
                                    }
                                },
                                {
                                    type: 'image_url',
                                    image_url: {
                                        url: `data:${candidateMime};base64,${candidateBase64}`,
                                        detail: 'high'
                                    }
                                }
                            ]
                        }
                    ],
                    max_tokens: 2048,
                    temperature: 0.3
                });

                const content = response.choices[0]?.message?.content;

                if (!content) {
                    throw new Error('No response generated by OpenAI Vision API');
                }

                return content;
            },
            { maxRetries: 2, timeoutMs: 70000 },
            'OpenAI Vision API (Comparison)'
        );
    }
}
